os: linux
language: node_js
node_js: 10
jobs:
  include:
    - name: "Test"
      install:
        - npm ci
        - npm install -g truffle@5.0.*
        - npm install -g ganache-cli
      before_script:
        - ganache-cli -m "spot pact fashion alert item unveil current choice emerge merge orient tribe" >ganache.log 2>&1 &
        - sleep 5
        - truffle migrate --network development
      script:
        - npm run test
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release -d
