os: linux
language: node_js
node_js: 10
jobs:
  include:
    - name: "Test"
      install:
        - npm ci
        - npm install -g truffle
        - npm install -g ganache-cli
      script: truffle test
